server:
  port: 8083

auth:
  enabled: false
  origin: "http://localhost:4200"
  jwt.key.set.uri: http://app-iam:8081/oauth2/jwks

spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:30307/RPBusinessEntityDB
    username: root
    password: your_database_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
    com.retailpulse: DEBUG
  file:
    name: logs/rp-businessentity.log

management:
  endpoints:
    web:
      exposure:
        include: "health"
    health:
      probes:
        enabled: true
      show-details: "never"